name: MyPushchair
favicon: null
layout_spectrum: 0.28356
typography_spectrum: 0.19224
title: 'Pushchair reviews, advice, best prices'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060000'
    - '#3c3c3c'
    - '#981a1d'
    - '#d44d54'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.4478353091981262
  rhythmicContrast: 0.5
purpose: []
